/**
 * Ma trận phân quyền toàn hệ thống WMS/ERP.
 * Mỗi giá trị tương ứng với privilege_code trong bảng privileges.
 * Dùng enum này thay vì hardcode string để đảm bảo type-safety.
 */
export enum Privilege {
  // ── PROCUREMENT ──
  VIEW_PO = 'VIEW_PO',
  CREATE_PO = 'CREATE_PO',
  UPDATE_PO = 'UPDATE_PO',
  APPROVE_PO = 'APPROVE_PO',
  EXPORT_PO = 'EXPORT_PO',

  // ── WMS ──
  VIEW_INVENTORY = 'VIEW_INVENTORY',
  RECEIVE_INBOUND = 'RECEIVE_INBOUND',
  SHIP_OUTBOUND = 'SHIP_OUTBOUND',
  EXPORT_INVENTORY = 'EXPORT_INVENTORY',
  MANAGE_INBOUND = 'MANAGE_INBOUND',
  MANAGE_INVENTORY = 'MANAGE_INVENTORY',
  MANAGE_OUTBOUND = 'MANAGE_OUTBOUND',

  // ── MASTER DATA ──
  MANAGE_PRODUCT = 'MANAGE_PRODUCT',
  MANAGE_SUPPLIER = 'MANAGE_SUPPLIER',
  MANAGE_MASTER_DATA = 'MANAGE_MASTER_DATA',
  IMPORT_MASTER_DATA = 'IMPORT_MASTER_DATA',
  EXPORT_MASTER_DATA = 'EXPORT_MASTER_DATA',

  // ── ADMIN (System) ──
  VIEW_USERS = 'VIEW_USERS',
  MANAGE_USER = 'MANAGE_USER',
  VIEW_ROLES = 'VIEW_ROLES',
  MANAGE_ROLE = 'MANAGE_ROLE',
  MANAGE_ORGANIZATION = 'MANAGE_ORGANIZATION',

  // ── HCM ──
  VIEW_EMPLOYEES = 'VIEW_EMPLOYEES',
  MANAGE_EMPLOYEE = 'MANAGE_EMPLOYEE',

  // ── TMS ──
  MANAGE_TMS = 'MANAGE_TMS',
  MANAGE_VEHICLE = 'MANAGE_VEHICLE',

  // ── PROJECT (Upcoming) ──
  VIEW_PROJECTS = 'VIEW_PROJECTS',
  MANAGE_PROJECTS = 'MANAGE_PROJECTS',
}
