export enum AssignmentRole {
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  MEMBER = 'MEMBER',
  SITE_SUPERVISOR = 'SITE_SUPERVISOR',
  SITE_DIRECTOR = 'SITE_DIRECTOR',
  SITE_QS = 'SITE_QS',
  SITE_ACCOUNTANT = 'SITE_ACCOUNTANT',
  SITE_ENGINEER = 'SITE_ENGINEER',
}
